### ISSUE TITLE
Image, LogModel, or LogEntry

### ISSUE THREAD

**Issue by gluo7777** [logproject/dev-log-service#2]
So I'm seeing these terms being thrown around and I was wondering how we should name the methods (e.g. getImage or getLogModel)?

**Comment by TheRealMarcusChiu** [comment]
Not sure why you are comparing getImage with getLogModel
But I sorda see what you mean. Here's the background on terms:
- `LogModel` is referring to a java object that represents a row in MySQL `log` table or document in MongoDB `log` collection. So ImageModel would be a java object that represents a row `image`and so forth. This is terminology is used in the community so its not just me. 
- `LogEntry` is something I'm using internally, to reference both the LogModel (the java object representation) and the `documents`which exists in our `log` collection. I think using `Log` would be a better term in some cases however, I would want to distinguish it between the already existing `log` collection.
